### ISSUE TITLE
Test site can withstand 15 concurrent users

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#595]
Going on estimates for targeted ads etc, @reddog worked out the following: 

 '8,000/month = 270/day.  Let's say that advertising is concentrated around a 6 hour window per day (for no particularly good reason other than to reduce down from a maximum 24 hour period), then we get 45 visitors/hour.  Let's say that 25% of them all come along at the same time (again, for no good reason, other than to aim high).  That would give about concurrent 12 users.  That's not high.  We could certainly create an issue to load test at 15-ish concurrent users - that would help show if the site will stand up or not. '

**Comment by katbow** [comment]
Note: 
Generally you would be able to load test different environments within the same file with a config like this:

```
  environments:
    prod:
      target: 'https://www.good-thinking.uk'
      phases:
        - duration: 60
          arrivalCount: 15
    local:
      target: 'http://127.0.0.1:8000'
      phases:
        - duration: 60
          arrivalCount: 15
```

and then pass the `-e` flag to the `artillery run` command, such as `artillery run -e prod file-name.yml`. However, because there are slight differences in urls, the scenarios cannot run in the same way.

If a scenario is defined as 

```
scenarios:
  - flow:
    - get:
        url: "/"
    - get:
        url: "/trouble-sleeping/"
    - get:
        url: "/resources/sleepstation/"
```

then it will try to go to those urls in the test. However, on production and local versions, some of those urls do not exist. In this case, rather than going through the sites/admin to ensure the urls match up, I am going to use separate files for staging and prod.

We can keep in mind for the future to ensure, if it's possible, that the urls match up between different sites.
